spring.application.name=freemarkerSSTI
server.port=8888
spring.freemarker.suffix=.ftl
spring.freemarker.content-type=text/html
spring.freemarker.charset=UTF-8
spring.freemarker.cache=false
spring.freemarker.template-loader-path=classpath:/templates/
spring.freemarker.expose-request-attributes=false
spring.freemarker.expose-session-attributes=false
spring.freemarker.expose-spring-macro-helpers=false
spring.freemarker.settings.new_builtin_class_resolver=safer

#management.endpoints.web.exposure.include=configprops
#management.endpoint.env.show-values=ALWAYS
#management.endpoint.configprops.access=unrestricted
#management.endpoint.caches.access=unrestricted
#management.endpoint.beans.access=unrestricted
#management.endpoint.configprops.sensitive=false

# logging.level.org.springframework=DEBUG


